magnetis/astro-tokens

- src/index.ts
- src/spaces/index.ts
Create `spaces` token
Spacing makes an interface more clear and harmonious. We use the below defined tokens for things such as padding, marging and positioning.
- Create tokens
- Create types
[AST-69](https://produtomagnetis.atlassian.net/browse/AST-69)
> [AST-69] Add spaces token

- src/fonts/index.ts
- src/index.ts
Create `fonts` token
Fonts makes a typography more conscious. We use the below defined tokens for things such as texts.
- Create tokens
- Create types
[AST-26](https://produtomagnetis.atlassian.net/browse/AST-26)
> [AST-26] Add fonts token

- src/index.ts
- src/sizes/index.ts
Create `sizes` token
Sizes makes a component more clear and harmonious. We use the below defined tokens for things such as width, height.
- Create tokens
- Create types
[AST-28](https://produtomagnetis.atlassian.net/browse/AST-28)
> [AST-28] Add sizes token

- src/colors/index.ts
- src/gradients/index.ts
- src/index.ts
Create `colors`  and `gradients` token
Colors and Gradients makes a component be colorful into our design system. We use the below defined tokens for things such as background colors and gradients.
- Create tokens
- Create types
[AST-25](https://produtomagnetis.atlassian.net/browse/AST-25)
[AST-27](https://produtomagnetis.atlassian.net/browse/AST-27)
> [AST-25] [AST-27] Add colors and gradients token

- .travis.yml
Update travis configuration
Automate deploy
N/A
N/A
N/A
> ci(.travis.yml): update travis config

- lint-staged.config.js
Remove jest from lint-staged
Remove jest from lint-staged
N/A
N/A
N/A
> fix(lint-staged): remove jest from lint-staged

- .eslintrc.yml
- package.json
Add test script to package.json
Add test script to package.json
N/A
N/A
N/A
> chore(package.json): add test script

- .travis.yml
Add email to travis config
N/A
N/A
N/A
N/A
> ci(.travis.config): add email

- package.json
Update package.json to release version.
> release(package): update version

- package.json
> Update version and entry point

- src/colors/index.ts
- src/fonts/index.ts
- src/gradients/index.ts
Remove type colors
TS infer automatically the colors types on usage.
[AST-81](https://produtomagnetis.atlassian.net/browse/AST-81)
> [AST-81] Fix type colors

- package.json
- tsconfig.json
- webpack.config.js
- yarn.lock
Configura o webpack para novos release
> Configure webpack for new release

- package.json
> release: bump version to 0.0.4

- package.json
> release: bump version to 0.0.6

- package.json
> release: version bump to 0.0.8

- lib/borders/index.d.ts
- lib/borders/index.js
- lib/colors/index.d.ts
- lib/colors/index.js
- lib/radius/index.d.ts
- lib/radius/index.js
- lib/shadows/index.d.ts
- lib/shadows/index.js
- lib/sizes/index.d.ts
- lib/sizes/index.js
- lib/typography/index.d.ts
- lib/typography/index.js
- tokens/tokens.json
- yarn.lock
> [AST-139] Add radii mini size

- .husky/pre-commit
- babel.config.cjs
- jest.config.js
- jest.setup.js
- package.json
- src/__tests__/helpers.test.ts
- src/formats.ts
- src/helpers.ts
- src/types.ts
- tsconfig.json
- yarn.lock
Add tests
To get more confidence while development
Add jest and configure tests with babel
Fetch from remote, switch to add-tests branch and run tests with `yarn test`
> Add tests to project

- .github/workflows/test.yml
- package.json
Add github action to lint and test on pull requests
To maintain project healthy and check all incoming code from pull requests
- Add `test:ci` command in `package.json` file
- Add `test` github action workflow
> Add github action for lint and test on pull requests

- .github/mention-to-slack.yml
- .github/workflows/slack-mention.yml
Add slack mention action to notify user or usergroup on slack when review is requeted
To simplify management and integration of code changes
Add a github action to notify users on slack
> chore: add slack mention action when request review

- lib/borders/index.d.ts
- lib/borders/index.js
- lib/colors/index.d.ts
- lib/colors/index.js
- lib/radius/index.d.ts
- lib/radius/index.js
- lib/shadows/index.d.ts
- lib/shadows/index.js
- lib/sizes/index.d.ts
- lib/sizes/index.js
- lib/typography/index.d.ts
- lib/typography/index.js
- tokens/tokens.json
Update tokens
To add missing tokens
Update tokens file and regenerate tokens
CONFIA-1277
> feat: update tokens file and re-generate tokens

- package.json
> chore: bump version to v0.0.9

- package.json
> chore: bump version to v0.0.10

- lib/borders/index.d.ts
- lib/borders/index.js
- lib/colors/index.d.ts
- lib/colors/index.js
- lib/radius/index.d.ts
- lib/radius/index.js
- lib/shadows/index.d.ts
- lib/shadows/index.js
- lib/sizes/index.d.ts
- lib/sizes/index.js
- lib/typography/index.d.ts
- lib/typography/index.js
- tokens/tokens.json
What
update solid-bright-lightest token
Why
The UX/UI team noticed that the new light gray color was lacking contrast on cell phones and found a new tone that would be visible on cell phones
How
Update tokens file and regenerate tokens
CONFIA-1431
> feat: update solid-bright-lighest color token

- package.json
> chore: bump version to v0.0.11
